apiVersion: v1 # Look at this in the template spec in kubernetes.io
data: # This is the actual content of the secret. Values need to be base 64 encoded
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
kind: Secret # Kind of resource
metadata:
  name: mongo-secret # This is the field used to reference this secret
type: Opaque # Standard type